### ISSUE TITLE
Question about fonts.

### ISSUE THREAD

**Issue by HaijunWei** [md-siam/package_of_the_day#1]
I'm very sorry, I can't reach you by email, I'm curious about the font and theme of this, can you tell me?

https://github.com/flutter/flutter/issues/102596#issuecomment-1111301596

**Comment by md-siam** [comment]
![Screen Shot 2022-10-11 at 10 35 07 AM](https://user-images.githubusercontent.com/21225918/194997911-70befd17-b0fc-4022-89a7-4068b138f2a5.png)

**Comment by md-siam** [comment]
Font: Operator Mono Lig
